--- #YAML:1.0
name:                Dancer-Plugin-SiteMap
version:             0.02
abstract:            Automated site map for the Dancer web framework.
license:             perl
author:
    - James Ronan <james@ronanweb.co.uk>
generated_by:        James Ronan
distribution_type:   module
requires:
    XML::Simple:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3